version: '3.2'

services:
    grafana:
        image: grafana/grafana-oss:10.0.3
        ports:
          - 3000:3000
        environment: 
          - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
        restart: unless-stopped
        volumes:
          - grafana-data-sources:/etc/grafana/provisioning/datasources
          - grafana-data:/var/lib/grafana
          - grafana-cred:/usr/share/grafana
    caddy:
        image: caddy:2
        restart: unless-stopped
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
        ports:
          - "443:443"
          - "80:80"
        depends_on:
          - grafana
      
volumes:
  grafana-data-sources:
  grafana-data:
  grafana-cred:
